name: dolabim
description: "A Flutter project integrated with Firebase Authentication and Firestore."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # iOS tarzı ikonlar
  cupertino_icons: ^1.0.8

  #  Firebase paketleri
  firebase_core: ^3.6.0        # Firebase'i başlatmak için
  firebase_auth: ^5.3.1        # Email/Password giriş sistemi
  cloud_firestore: ^5.4.4      # Firestore veritabanı
#fotoğrafı bunla çekicez ya da yüklücez
  image_picker: ^1.1.2
  #  Shimmer efekti (altın parlama için)
  shimmer: ^3.0.0

  # (isteğe bağlı) Gelişmiş animasyonlar için
  # flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #  Görsellerin ve logoların kullanılabilmesi için aktif hale getirildi
  assets:
    - assets/images/glamora_logo.png
    - assets/images/glamora_harf_logo.png
