name: dolabim
description: "A Flutter project integrated with Firebase Authentication and Supabase Storage."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # iOS tarzÄ± ikonlar
  cupertino_icons: ^1.0.8

  #  Firebase paketleri
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

  #  Firestore artÄ±k zorunlu deÄŸil ama istersen kalabilir
  # cloud_firestore: ^5.4.4

  #  Supabase paketi (Storage + Database)
  supabase_flutter: ^2.5.8

  #  FotoÄŸraf seÃ§mek veya Ã§ekmek iÃ§in
  image_picker: ^1.1.2

  #  Shimmer efekti
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ğŸ–¼ GÃ¶rseller
  assets:
    - assets/images/glamora_logo.png
    - assets/images/glamora_harf_logo.png
