name: dolabim
description: "A Flutter project integrated with Firebase Authentication and Firestore."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # --- Flutter UI / Icon ---
  cupertino_icons: ^1.0.8

  # --- Firebase Bağımlılıkları ---
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4       # Firestore veritabanı
  firebase_storage: ^12.3.2
  cloud_functions: ^5.1.1

  # --- HTTP istekleri için ---
  http: ^1.2.1

  # --- Görsel ve Renk Analizi ---
  fl_chart: ^0.66.0             # PieChart, LineChart, vs.
  palette_generator: ^0.3.3+5   # Görselden renk paleti çıkarma

  # --- Fotoğraf Seçme / Yükleme ---
  image_picker: ^1.1.2          # Kamera veya galeri erişimi

  # --- Efekt ve Animasyonlar ---
  shimmer: ^3.0.0               # Altın parlama efekti
  flutter_animate: ^4.5.0       # Ek animasyon efektleri

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/glamora_logo.png
    - assets/images/glamora_harf_logo.png
